[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.160.1"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
